"""Create signals table for DecisionEngine Service

Revision ID: ab79d1c7c055
Revises: 30eb898ddf84
Create Date: 2025-11-10 16:26:23.179560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab79d1c7c055'
down_revision: Union[str, None] = '30eb898ddf84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('market', sa.String(length=50), nullable=False, comment='Trading pair, e.g., BTC/USDT'),
    sa.Column('signal_type', sa.String(length=20), nullable=False, comment='Signal type: PULLBACK_BUY, OOPS_BUY, OOPS_SELL'),
    sa.Column('entry_price', sa.DECIMAL(precision=18, scale=8), nullable=False, comment='Suggested entry price'),
    sa.Column('stop_loss_price', sa.DECIMAL(precision=18, scale=8), nullable=False, comment='Initial stop loss price'),
    sa.Column('profit_target_price', sa.DECIMAL(precision=18, scale=8), nullable=False, comment='Profit target price'),
    sa.Column('risk_unit_r', sa.DECIMAL(precision=18, scale=8), nullable=False, comment='Risk unit (R) in quote currency'),
    sa.Column('suggested_position_weight', sa.DECIMAL(precision=5, scale=4), nullable=False, comment='Suggested position weight (0.0000-1.0000), calculated based on rule_engine_score'),
    sa.Column('reward_risk_ratio', sa.DECIMAL(precision=5, scale=2), nullable=True, comment='Reward/Risk ratio, e.g., 2.50 means 2.5:1'),
    sa.Column('onchain_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='OnChain data signals in JSON format'),
    sa.Column('rule_engine_score', sa.Float(), nullable=False, comment='Rule engine confidence score (0-100)'),
    sa.Column('ml_confidence_score', sa.Float(), nullable=True, comment='ML model confidence score (0-100), Phase 2'),
    sa.Column('llm_sentiment', sa.String(length=20), nullable=True, comment='LLM sentiment analysis result, Phase 2'),
    sa.Column('final_decision', sa.String(length=20), nullable=True, comment='Final arbitration decision: APPROVED/REJECTED/PENDING, Phase 2'),
    sa.Column('explanation', sa.Text(), nullable=True, comment='Explanation for the decision, Phase 2'),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False, comment='Signal creation timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signal_market_created', 'signals', ['market', 'created_at'], unique=False)
    op.create_index('idx_signal_score', 'signals', ['rule_engine_score'], unique=False)
    op.create_index('idx_signal_type_created', 'signals', ['signal_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_signals_created_at'), 'signals', ['created_at'], unique=False)
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    op.create_index(op.f('ix_signals_market'), 'signals', ['market'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_market'), table_name='signals')
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_index(op.f('ix_signals_created_at'), table_name='signals')
    op.drop_index('idx_signal_type_created', table_name='signals')
    op.drop_index('idx_signal_score', table_name='signals')
    op.drop_index('idx_signal_market_created', table_name='signals')
    op.drop_table('signals')
    # ### end Alembic commands ###

