"""datahub_add_kline_and_onchain_models

Revision ID: 30eb898ddf84
Revises: 
Create Date: 2025-11-10 03:50:21.481047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30eb898ddf84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('klines',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('open_time', sa.BigInteger(), nullable=False),
    sa.Column('close_time', sa.BigInteger(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('quote_volume', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.BigInteger(), nullable=True),
    sa.Column('taker_buy_base_volume', sa.Float(), nullable=True),
    sa.Column('taker_buy_quote_volume', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kline_source_symbol', 'klines', ['source', 'symbol'], unique=False)
    op.create_index('idx_kline_symbol_interval_time', 'klines', ['symbol', 'interval', 'open_time'], unique=False)
    op.create_index(op.f('ix_klines_id'), 'klines', ['id'], unique=False)
    op.create_index(op.f('ix_klines_interval'), 'klines', ['interval'], unique=False)
    op.create_index(op.f('ix_klines_open_time'), 'klines', ['open_time'], unique=False)
    op.create_index(op.f('ix_klines_symbol'), 'klines', ['symbol'], unique=False)
    op.create_table('onchain_metrics',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('network', sa.String(length=50), nullable=False),
    sa.Column('contract_address', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.BigInteger(), nullable=False),
    sa.Column('transaction_count', sa.BigInteger(), nullable=True),
    sa.Column('transaction_volume', sa.Float(), nullable=True),
    sa.Column('transaction_volume_usd', sa.Float(), nullable=True),
    sa.Column('active_addresses', sa.BigInteger(), nullable=True),
    sa.Column('new_addresses', sa.BigInteger(), nullable=True),
    sa.Column('dex_volume_usd', sa.Float(), nullable=True),
    sa.Column('dex_trade_count', sa.BigInteger(), nullable=True),
    sa.Column('dex_buyer_count', sa.BigInteger(), nullable=True),
    sa.Column('dex_seller_count', sa.BigInteger(), nullable=True),
    sa.Column('liquidity_usd', sa.Float(), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('additional_metrics', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_onchain_contract', 'onchain_metrics', ['contract_address'], unique=False)
    op.create_index('idx_onchain_network_symbol', 'onchain_metrics', ['network', 'symbol'], unique=False)
    op.create_index('idx_onchain_symbol_timestamp', 'onchain_metrics', ['symbol', 'timestamp'], unique=False)
    op.create_index(op.f('ix_onchain_metrics_contract_address'), 'onchain_metrics', ['contract_address'], unique=False)
    op.create_index(op.f('ix_onchain_metrics_id'), 'onchain_metrics', ['id'], unique=False)
    op.create_index(op.f('ix_onchain_metrics_network'), 'onchain_metrics', ['network'], unique=False)
    op.create_index(op.f('ix_onchain_metrics_symbol'), 'onchain_metrics', ['symbol'], unique=False)
    op.create_index(op.f('ix_onchain_metrics_timestamp'), 'onchain_metrics', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_onchain_metrics_timestamp'), table_name='onchain_metrics')
    op.drop_index(op.f('ix_onchain_metrics_symbol'), table_name='onchain_metrics')
    op.drop_index(op.f('ix_onchain_metrics_network'), table_name='onchain_metrics')
    op.drop_index(op.f('ix_onchain_metrics_id'), table_name='onchain_metrics')
    op.drop_index(op.f('ix_onchain_metrics_contract_address'), table_name='onchain_metrics')
    op.drop_index('idx_onchain_symbol_timestamp', table_name='onchain_metrics')
    op.drop_index('idx_onchain_network_symbol', table_name='onchain_metrics')
    op.drop_index('idx_onchain_contract', table_name='onchain_metrics')
    op.drop_table('onchain_metrics')
    op.drop_index(op.f('ix_klines_symbol'), table_name='klines')
    op.drop_index(op.f('ix_klines_open_time'), table_name='klines')
    op.drop_index(op.f('ix_klines_interval'), table_name='klines')
    op.drop_index(op.f('ix_klines_id'), table_name='klines')
    op.drop_index('idx_kline_symbol_interval_time', table_name='klines')
    op.drop_index('idx_kline_source_symbol', table_name='klines')
    op.drop_table('klines')
    # ### end Alembic commands ###

